### ISSUE TITLE
TOC section 5.6 text is garbled

### ISSUE THREAD

**Issue by wkande** [api3dao/api3-whitepaper#2]
Check the TOC in version 1.0.1 of the Whitepaper for section 5.6. There is garbled text. Image attached.

![garbled text TOC](https://user-images.githubusercontent.com/3522283/113607636-a8268900-9606-11eb-91d2-3932969c51dc.png)

**Comment by bbenligiray** [comment]
I had fixed that but I forgot to update the release, did that now. I won't bump a version number for this.
