### ISSUE TITLE
"B" in Figure 8 is confusing

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-whitepaper#4]
There is a "B" in the middle of the systems diagram in Figure 8.a. This indicates that the loop is a balanced one due to the negative feedback
https://en.wikipedia.org/wiki/Causal_loop_diagram#Reinforcing_and_balancing_loops
yet this may not be obvious for people not familiar with the convention. What that "B" is should be stated explicitly in the caption.

**Comment by dcroote** [comment]
Perhaps the caption: 
https://github.com/api3dao/api3-whitepaper/blob/8e010ba9809fe9ca80402b9671347cfc8ae970ea/api3-whitepaper.tex#L735
can be supplemented to include:
"...and balances the system **as depicted by the balancing loop at center**."

**Comment by bbenligiray** [comment]
Addressed in https://github.com/api3dao/api3-whitepaper/releases/tag/v1.0.2
